/*
 * NativeMP3Decoder.h
 *
 *  Created on: 2015Äê2ÔÂ6ÈÕ
 *      Author: Administrator
 */

#ifndef NATIVEMP3DECODER_H_
#define NATIVEMP3DECODER_H_

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <stdlib.h>

extern "C" {
//
int NativeMP3Decoder_init(char const* filepath,unsigned long start/*,unsigned long size*/);

int NativeMP3Decoder_readSamples(short *target, int size);

void NativeMP3Decoder_closeAduioFile();

int NativeMP3Decoder_getAduioSamplerate();

}
#endif /* NATIVEMP3DECODER_H_ */
